// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vngbogvthjxfdejikfea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZ2JvZ3Z0aGp4ZmRlamlrZmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTU5NzUsImV4cCI6MjA2NTA3MTk3NX0.GGRq09hS0adMGKGW0D0d2m9MT4jAFgnomf9M6-KYQ2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);